/**
 * Skill Bridge Platform - Realistic Domain Dataset Layer
 * File: lib/dummy-data/index.js
 * 
 * Provides comprehensive, high-fidelity mock and live seed domain data for:
 * - studentData (Profile, 5-Level Evidence Skill Matrix, Opportunities, 6-Stage Applications, Gap Upskilling)
 * - industryData (Org Profile, Published Jobs with Gatekeeper Stats, Candidates, Post-Internship L5 Evals)
 * - instituteData (Readiness Benchmarks, Privacy-Preserving k-anonymity Skill Gap Alerts, Workshops, Feedback)
 * - adminData (Platform KPIs, KYC Queue, Forensic Audit Logs, System Health)
 */

export const studentData = {
  profile: {
    id: "std_001",
    userId: "usr_001",
    name: "Aarav Sharma",
    email: "aarav.sharma@example.edu",
    rollNumber: "CS2026-001",
    instituteName: "Indian Institute of Information Technology & Engineering",
    department: "Computer Science & Engineering",
    degree: "B.Tech in Computer Science",
    yearOfStudy: "4th Year",
    graduationYear: 2026,
    cgpa: 8.9,
    headline: "Aspiring Data Analyst & Full-Stack Developer | Python • SQL • Next.js",
    bio: "Senior Computer Science undergraduate specializing in data analytics, database query optimization, and dashboard engineering. Seeking high-impact internship and full-time opportunities in data and product engineering.",
    phone: "+91 98765 43210",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    profileCompletion: 78,
    careerPreferences: {
      preferredRoles: ["Data Analyst", "Data Engineer", "Full Stack Developer"],
      preferredLocations: ["Bengaluru", "Remote", "Pune", "Hyderabad"],
      expectedStipend: "₹35,000 / month",
      jobTypes: ["Internship", "Full-Time Placement"],
    },
  },

  skillMatrix: [
    {
      id: "sk_01",
      name: "Python",
      canonicalName: "Python",
      category: "Programming Languages",
      proficiency: 3,
      proficiencyLabel: "Advanced",
      evidenceLevel: 4,
      evidenceLabel: "Level 4 — Project Verified",
      evidenceUrl: "https://github.com/aarav-sharma/py-data-tools",
      verification: "Project / Portfolio Verified",
      confidenceScore: 92,
      isIndustryVerified: false,
    },
    {
      id: "sk_02",
      name: "SQL",
      canonicalName: "SQL",
      category: "Database & Querying",
      proficiency: 3,
      proficiencyLabel: "Advanced",
      evidenceLevel: 3,
      evidenceLabel: "Level 3 — Assessment Verified",
      evidenceUrl: "https://cert.hackerrank.com/sql-adv-aarav",
      verification: "Assessment Verified",
      confidenceScore: 88,
      isIndustryVerified: false,
    },
    {
      id: "sk_03",
      name: "Data Analysis",
      canonicalName: "Data Analysis",
      category: "Data Science & AI",
      proficiency: 3,
      proficiencyLabel: "Advanced",
      evidenceLevel: 4,
      evidenceLabel: "Level 4 — Project Verified",
      evidenceUrl: "https://github.com/aarav-sharma/sales-insights",
      verification: "Project Verified",
      confidenceScore: 94,
      isIndustryVerified: false,
    },
    {
      id: "sk_04",
      name: "Statistics",
      canonicalName: "Statistics",
      category: "Data Science & AI",
      proficiency: 2,
      proficiencyLabel: "Intermediate",
      evidenceLevel: 2,
      evidenceLabel: "Level 2 — Course Certificate",
      evidenceUrl: "https://nptel.ac.in/verify/stats-aarav",
      verification: "Coursework / NPTEL",
      confidenceScore: 84,
      isIndustryVerified: false,
    },
    {
      id: "sk_05",
      name: "Power BI",
      canonicalName: "Power BI",
      category: "Data Science & AI",
      proficiency: 2,
      proficiencyLabel: "Intermediate",
      evidenceLevel: 3,
      evidenceLabel: "Level 3 — Assessment Verified",
      evidenceUrl: "https://learn.microsoft.com/powerbi/aarav",
      verification: "Assessment Verified",
      confidenceScore: 86,
      isIndustryVerified: false,
    },
    {
      id: "sk_06",
      name: "Tableau",
      canonicalName: "Tableau",
      category: "Data Science & AI",
      proficiency: 2,
      proficiencyLabel: "Intermediate",
      evidenceLevel: 2,
      evidenceLabel: "Level 2 — Course Certificate",
      evidenceUrl: "https://public.tableau.com/profile/aarav",
      verification: "Certificate",
      confidenceScore: 80,
      isIndustryVerified: false,
    },
    {
      id: "sk_07",
      name: "Excel",
      canonicalName: "Excel",
      category: "Data Science & AI",
      proficiency: 3,
      proficiencyLabel: "Advanced",
      evidenceLevel: 3,
      evidenceLabel: "Level 3 — Assessment Verified",
      evidenceUrl: "https://coursera.org/verify/excel-aarav",
      verification: "Assessment Verified",
      confidenceScore: 88,
      isIndustryVerified: false,
    },
    {
      id: "sk_08",
      name: "React",
      canonicalName: "React",
      category: "Frontend Development",
      proficiency: 2,
      proficiencyLabel: "Intermediate",
      evidenceLevel: 2,
      evidenceLabel: "Level 2 — Certificate",
      evidenceUrl: "https://github.com/aarav-sharma/react-portfolio",
      verification: "Certificate",
      confidenceScore: 78,
      isIndustryVerified: false,
    },
    {
      id: "sk_09",
      name: "Machine Learning",
      canonicalName: "Machine Learning",
      category: "Data Science & AI",
      proficiency: 1,
      proficiencyLabel: "Beginner",
      evidenceLevel: 1,
      evidenceLabel: "Level 1 — Self Declared",
      evidenceUrl: "",
      verification: "Self Declared",
      confidenceScore: 60,
      isIndustryVerified: false,
    },
  ],

  recommendedOpportunities: [
    {
      id: "opp_001",
      title: "Data Analyst Intern",
      roleTitle: "Data Analyst Internship",
      company: "TechCorp Global",
      companyName: "Apex Analytics Corp",
      location: "Bengaluru (Hybrid)",
      type: "Internship",
      stipend: "₹35,000 / month",
      duration: "6 Months",
      openings: 5,
      status: "ACTIVE",
      mandatoryMatch: 100,
      preferredMatch: 75,
      compositeScore: 92.5,
      isEligible: true,
      gateStatus: "ELIGIBLE - FULL GATE PASSED",
      deadline: "2026-09-30",
      description: "Join our core analytics division to convert enterprise data into actionable intelligence. Construct SQL queries, perform EDA in Python, and build dashboards in Tableau & Power BI.",
      highPrioritySkills: [
        { name: "Python", requiredProficiency: 2, studentProficiency: 3, matched: true },
        { name: "SQL", requiredProficiency: 2, studentProficiency: 3, matched: true },
        { name: "Data Analysis", requiredProficiency: 3, studentProficiency: 3, matched: true },
        { name: "Statistics", requiredProficiency: 2, studentProficiency: 2, matched: true },
      ],
      preferredSkills: [
        { name: "Power BI", requiredProficiency: 1, studentProficiency: 2, matched: true },
        { name: "Tableau", requiredProficiency: 1, studentProficiency: 2, matched: true },
        { name: "Excel", requiredProficiency: 3, studentProficiency: 3, matched: true },
        { name: "Machine Learning", requiredProficiency: 1, studentProficiency: 1, matched: true },
      ],
      missingPreferred: [],
      missingMandatory: [],
    },
    {
      id: "opp_005",
      title: "Financial Analytics Associate",
      roleTitle: "Financial Analytics Associate",
      company: "FinTech Innovations",
      companyName: "FinTech Global Innovations",
      location: "Mumbai (On-Site)",
      type: "Full-Time Placement",
      stipend: "₹10,00,000 / annum",
      duration: "Permanent",
      openings: 3,
      status: "ACTIVE",
      mandatoryMatch: 100,
      preferredMatch: 100,
      compositeScore: 100.0,
      isEligible: true,
      gateStatus: "ELIGIBLE - 100% FULL MATCH",
      deadline: "2026-09-15",
      description: "Build financial predictive models, quantitative reports, and automated reporting systems for enterprise wealth management clients.",
      highPrioritySkills: [
        { name: "SQL", requiredProficiency: 3, studentProficiency: 3, matched: true },
        { name: "Excel", requiredProficiency: 3, studentProficiency: 3, matched: true },
        { name: "Data Analysis", requiredProficiency: 3, studentProficiency: 3, matched: true },
        { name: "Python", requiredProficiency: 2, studentProficiency: 3, matched: true },
      ],
      preferredSkills: [
        { name: "Power BI", requiredProficiency: 2, studentProficiency: 2, matched: true },
      ],
      missingPreferred: [],
      missingMandatory: [],
    },
    {
      id: "opp_009",
      title: "Business Intelligence Specialist",
      roleTitle: "BI & Dashboard Specialist",
      company: "RetailWave Commerce",
      companyName: "ByteWave Technologies",
      location: "Bengaluru (Hybrid)",
      type: "Full-Time Placement",
      stipend: "₹7,50,000 / annum",
      duration: "Permanent",
      openings: 4,
      status: "ACTIVE",
      mandatoryMatch: 100,
      preferredMatch: 100,
      compositeScore: 100.0,
      isEligible: true,
      gateStatus: "ELIGIBLE - 100% FULL MATCH",
      deadline: "2026-09-20",
      description: "Design and implement executive analytics dashboards in Power BI and Tableau with relational SQL data warehouses.",
      highPrioritySkills: [
        { name: "Power BI", requiredProficiency: 2, studentProficiency: 2, matched: true },
        { name: "SQL", requiredProficiency: 2, studentProficiency: 3, matched: true },
        { name: "Excel", requiredProficiency: 3, studentProficiency: 3, matched: true },
      ],
      preferredSkills: [
        { name: "Tableau", requiredProficiency: 2, studentProficiency: 2, matched: true },
        { name: "Statistics", requiredProficiency: 2, studentProficiency: 2, matched: true },
      ],
      missingPreferred: [],
      missingMandatory: [],
    },
    {
      id: "opp_004",
      title: "Machine Learning Research Intern",
      roleTitle: "ML Research Intern",
      company: "DataScale Labs",
      companyName: "HealthPulse AI",
      location: "Hyderabad (Hybrid)",
      type: "Internship",
      stipend: "₹45,000 / month",
      duration: "6 Months",
      openings: 2,
      status: "ACTIVE",
      mandatoryMatch: 67,
      preferredMatch: 50,
      compositeScore: 61.9,
      isEligible: false,
      gateStatus: "NOT ELIGIBLE - MANDATORY SKILL GAP",
      deadline: "2026-09-25",
      description: "Conduct research in medical imaging and generative AI pipelines using deep neural networks and PyTorch.",
      highPrioritySkills: [
        { name: "Python", requiredProficiency: 3, studentProficiency: 3, matched: true },
        { name: "Statistics", requiredProficiency: 3, studentProficiency: 2, matched: false },
        { name: "Machine Learning", requiredProficiency: 3, studentProficiency: 1, matched: false },
      ],
      preferredSkills: [
        { name: "PyTorch", requiredProficiency: 2, studentProficiency: 0, matched: false },
        { name: "Docker", requiredProficiency: 1, studentProficiency: 0, matched: false },
      ],
      missingMandatory: ["Machine Learning (Req L3, Have L1)", "Statistics (Req L3, Have L2)"],
      missingPreferred: ["PyTorch", "Docker"],
    },
    {
      id: "opp_003",
      title: "Backend Node.js & Cloud Engineer",
      roleTitle: "Backend Node.js & Cloud Engineer",
      company: "CloudPeak Systems",
      companyName: "CloudScale Systems",
      location: "Pune (On-Site)",
      type: "Full-Time Placement",
      stipend: "₹8,50,000 / annum",
      duration: "Permanent",
      openings: 3,
      status: "ACTIVE",
      mandatoryMatch: 33,
      preferredMatch: 50,
      compositeScore: 38.1,
      isEligible: false,
      gateStatus: "NOT ELIGIBLE - MANDATORY SKILL GAP",
      deadline: "2026-09-18",
      description: "Build microservices, asynchronous message queues, and containerized cloud services.",
      highPrioritySkills: [
        { name: "Node.js", requiredProficiency: 3, studentProficiency: 0, matched: false },
        { name: "PostgreSQL", requiredProficiency: 2, studentProficiency: 2, matched: true },
        { name: "Docker", requiredProficiency: 2, studentProficiency: 0, matched: false },
      ],
      preferredSkills: [
        { name: "AWS", requiredProficiency: 2, studentProficiency: 0, matched: false },
        { name: "TypeScript", requiredProficiency: 2, studentProficiency: 0, matched: false },
      ],
      missingMandatory: ["Node.js", "Docker"],
      missingPreferred: ["AWS", "TypeScript"],
    },
  ],

  applicationHistory: [
    {
      id: "app_001",
      opportunityId: "opp_001",
      roleTitle: "Data Analyst Intern",
      companyName: "Apex Analytics Corp",
      companyLogo: "/logos/apex.png",
      status: "SHORTLISTED",
      stage: 3,
      totalStages: 6,
      stageLabel: "Shortlisted for Interview",
      appliedDate: "2026-08-16",
      mandatoryMatch: 100,
      preferredMatch: 75,
      compositeScore: 92.5,
      nextStep: "Technical Assessment & Video Interview scheduled on Aug 28, 2026",
      timeline: [
        { status: "APPLIED", date: "2026-08-16", note: "Application submitted with 100% High-Priority Gate Clearance" },
        { status: "UNDER_REVIEW", date: "2026-08-18", note: "Portfolio reviewed by lead recruiter Vikram Malhotra" },
        { status: "SHORTLISTED", date: "2026-08-22", note: "Moved to shortlist pool (Top 10 percentile candidate)" },
      ],
    },
    {
      id: "app_002",
      opportunityId: "opp_005",
      roleTitle: "Financial Analytics Associate",
      companyName: "FinTech Global Innovations",
      companyLogo: "/logos/fintech.png",
      status: "INTERVIEW",
      stage: 4,
      totalStages: 6,
      stageLabel: "Interview Round Active",
      appliedDate: "2026-08-14",
      mandatoryMatch: 100,
      preferredMatch: 100,
      compositeScore: 100.0,
      nextStep: "Final Partner Evaluation on Aug 27, 2026 at 3:00 PM IST",
      timeline: [
        { status: "APPLIED", date: "2026-08-14", note: "Applied with 100% match profile" },
        { status: "UNDER_REVIEW", date: "2026-08-15", note: "Automated gatekeeper passed" },
        { status: "SHORTLISTED", date: "2026-08-17", note: "Selected for round 1" },
        { status: "INTERVIEW", date: "2026-08-21", note: "Technical round completed successfully (Rating 4.9/5)" },
      ],
    },
    {
      id: "app_003",
      opportunityId: "opp_009",
      roleTitle: "Business Intelligence Specialist",
      companyName: "RetailWave Commerce",
      companyLogo: "/logos/retailwave.png",
      status: "UNDER_REVIEW",
      stage: 2,
      totalStages: 6,
      stageLabel: "Under Hiring Team Review",
      appliedDate: "2026-08-18",
      mandatoryMatch: 100,
      preferredMatch: 100,
      compositeScore: 100.0,
      nextStep: "Recruiter screening expected within 3 business days",
      timeline: [
        { status: "APPLIED", date: "2026-08-18", note: "Application received and logged" },
        { status: "UNDER_REVIEW", date: "2026-08-19", note: "Skills verified by system gatekeeper" },
      ],
    },
    {
      id: "app_004",
      opportunityId: "opp_002",
      roleTitle: "Frontend React Developer Intern",
      companyName: "TechCorp Global",
      companyLogo: "/logos/techcorp.png",
      status: "APPLIED",
      stage: 1,
      totalStages: 6,
      stageLabel: "Application Submitted",
      appliedDate: "2026-08-20",
      mandatoryMatch: 100,
      preferredMatch: 50,
      compositeScore: 85.0,
      nextStep: "Awaiting recruiter queue review",
      timeline: [
        { status: "APPLIED", date: "2026-08-20", note: "Applied with verified React L2 credentials" },
      ],
    },
    {
      id: "app_005",
      opportunityId: "opp_010",
      roleTitle: "Cloud & Data Engineering Trainee",
      companyName: "CloudPeak Systems",
      companyLogo: "/logos/cloudpeak.png",
      status: "SELECTED",
      stage: 5,
      totalStages: 6,
      stageLabel: "Offer Extended",
      appliedDate: "2026-07-28",
      mandatoryMatch: 100,
      preferredMatch: 100,
      compositeScore: 100.0,
      nextStep: "Review and accept official offer letter by Sept 05, 2026",
      timeline: [
        { status: "APPLIED", date: "2026-07-28", note: "Applied" },
        { status: "UNDER_REVIEW", date: "2026-08-01", note: "Profile screened" },
        { status: "SHORTLISTED", date: "2026-08-05", note: "Shortlisted" },
        { status: "INTERVIEW", date: "2026-08-10", note: "Completed 2 technical rounds" },
        { status: "SELECTED", date: "2026-08-18", note: "Formal offer issued — ₹38,000/mo stipend" },
      ],
    },
    {
      id: "app_006",
      opportunityId: "opp_004",
      roleTitle: "AI/ML Systems Research Associate",
      companyName: "DataScale Labs",
      companyLogo: "/logos/datascale.png",
      status: "REJECTED",
      stage: 6,
      totalStages: 6,
      stageLabel: "Candidate Not Eligible",
      appliedDate: "2026-08-05",
      mandatoryMatch: 67,
      preferredMatch: 50,
      compositeScore: 61.9,
      nextStep: "Target missing mandatory skills in upskilling module",
      timeline: [
        { status: "APPLIED", date: "2026-08-05", note: "Applied" },
        { status: "REJECTED", date: "2026-08-06", note: "Gatekeeper mismatch: Missing Mandatory Machine Learning Level 3" },
      ],
    },
  ],

  gapUpskilling: [
    {
      id: "gap_01",
      skillName: "Machine Learning",
      targetProficiency: "Level 3 (Advanced)",
      currentProficiency: "Level 1 (Beginner)",
      evidenceGap: "Missing evidence badge",
      impact: "Unlocks 12 AI & Data Science roles (₹45k/mo avg)",
      recommendedAction: "Enroll in Institute Workshop: Applied Machine Learning with Scikit-Learn",
      actionUrl: "/institute/training",
      provider: "IIITE Faculty + Industry Partner",
      duration: "4 Weeks (32 Hours)",
      status: "AVAILABLE",
    },
    {
      id: "gap_02",
      skillName: "Docker & Containerization",
      targetProficiency: "Level 2 (Intermediate)",
      currentProficiency: "Level 0 (Unlisted)",
      evidenceGap: "Needs Assessment verification",
      impact: "Unlocks 8 Cloud & Backend placement tracks",
      recommendedAction: "Take Skill Bridge Assessment for Docker Level 2",
      actionUrl: "/student/skills",
      provider: "Skill Bridge Assessment Engine",
      duration: "30 Mins (Timed)",
      status: "READY_TO_START",
    },
    {
      id: "gap_03",
      skillName: "PostgreSQL Advanced Optimization",
      targetProficiency: "Level 3 (Advanced)",
      currentProficiency: "Level 2 (Intermediate)",
      evidenceGap: "Upgrade to Level 4 Project Verified",
      impact: "Boosts candidate composite score to 98% for Database Engineer roles",
      recommendedAction: "Submit GitHub ETL Project repository for automated code proof verification",
      actionUrl: "/student/profile",
      provider: "Skill Bridge Portfolio Verifier",
      duration: "Self-paced",
      status: "AVAILABLE",
    },
  ],
};

export const industryData = {
  profile: {
    id: "comp_001",
    userId: "usr_rec_01",
    companyName: "Apex Analytics Corp",
    brandName: "TechCorp Global",
    industry: "Big Data, Cloud Analytics & Business Intelligence",
    sector: "Enterprise Software & Analytics",
    companySize: "250 - 500 Employees",
    registrationNumber: "U72200KA2021PTC145892",
    taxIdGstin: "29ABCDE1234F1Z5",
    website: "https://apexanalytics.com",
    location: "Bengaluru, Karnataka (HQ)",
    contactEmail: "talent@apexanalytics.com",
    contactPhone: "+91 80 4123 4567",
    logoUrl: "/logos/apex.png",
    verified: true,
    kycStatus: "APPROVED",
    recruiterName: "Vikram Malhotra",
    recruiterRole: "Senior Director of Campus Talent Acquisition",
    profileCompletion: 92,
  },

  kpiStats: {
    activeRoles: 6,
    totalApplicants: 142,
    gatePassedApplicants: 68,
    gateFilteredOut: 74,
    interviewing: 18,
    offersExtended: 7,
    pendingEvaluations: 4,
    zeroNoiseRate: "52% Noise Eliminated by Gatekeeper",
    avgMatchScore: "94.6%",
    timeToShortlist: "1.2 Days (vs industry avg 14 days)",
  },

  publishedJobs: [
    {
      id: "opp_001",
      title: "Data Analyst Intern",
      roleTitle: "Data Analyst Internship",
      department: "Enterprise Analytics",
      location: "Bengaluru (Hybrid)",
      type: "Internship",
      stipend: "₹35,000 / month",
      duration: "6 Months",
      openings: 5,
      status: "ACTIVE",
      postedDate: "2026-08-15",
      deadline: "2026-09-30",
      applicantsCount: 38,
      eligibleCount: 18,
      partialMatchCount: 12,
      filteredOutCount: 8,
      mandatorySkills: ["Python (L2)", "SQL (L2)", "Data Analysis (L3)", "Statistics (L2)"],
      preferredSkills: ["Power BI (L1)", "Tableau (L1)", "Excel (L3)", "Machine Learning (L1)"],
    },
    {
      id: "opp_002",
      title: "Senior Data Pipeline Engineer",
      roleTitle: "Senior Data Pipeline Engineer",
      department: "Data Platform Engineering",
      location: "Bengaluru (On-Site)",
      type: "Full-Time Placement",
      stipend: "₹14,00,000 / annum",
      duration: "Permanent",
      openings: 2,
      status: "ACTIVE",
      postedDate: "2026-08-10",
      deadline: "2026-09-20",
      applicantsCount: 24,
      eligibleCount: 9,
      partialMatchCount: 7,
      filteredOutCount: 8,
      mandatorySkills: ["Python (L3)", "PostgreSQL (L3)", "Apache Spark (L2)", "SQL (L3)"],
      preferredSkills: ["AWS (L2)", "Docker (L2)", "Kubernetes (L1)"],
    },
    {
      id: "opp_003",
      title: "Business Intelligence Associate",
      roleTitle: "BI & Analytics Associate",
      department: "Commercial Operations",
      location: "Bengaluru (Hybrid)",
      type: "Full-Time Placement",
      stipend: "₹7,50,000 / annum",
      duration: "Permanent",
      openings: 4,
      status: "ACTIVE",
      postedDate: "2026-08-12",
      deadline: "2026-09-25",
      applicantsCount: 45,
      eligibleCount: 26,
      partialMatchCount: 14,
      filteredOutCount: 5,
      mandatorySkills: ["Power BI (L3)", "SQL (L2)", "Excel (L3)"],
      preferredSkills: ["Tableau (L2)", "Statistics (L2)"],
    },
    {
      id: "opp_004",
      title: "Quantitative Research Intern",
      roleTitle: "Quantitative Analytics Intern",
      department: "Financial Intelligence",
      location: "Remote",
      type: "Internship",
      stipend: "₹40,000 / month",
      duration: "6 Months",
      openings: 2,
      status: "ACTIVE",
      postedDate: "2026-08-18",
      deadline: "2026-09-28",
      applicantsCount: 35,
      eligibleCount: 15,
      partialMatchCount: 11,
      filteredOutCount: 9,
      mandatorySkills: ["Python (L3)", "Statistics (L3)", "SQL (L2)"],
      preferredSkills: ["Machine Learning (L2)", "R Programming (L1)"],
    },
  ],

  talentSearchCandidates: [
    {
      id: "std_002",
      name: "Priya Patel",
      institute: "IIITE Bengaluru",
      department: "Data Science & AI",
      year: "4th Year",
      cgpa: 9.4,
      mandatoryMatch: 100,
      preferredMatch: 100,
      compositeScore: 100.0,
      gateStatus: "ELIGIBLE - FULL MATCH",
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150",
      topSkills: [
        { name: "Python", evidenceLevel: 4, verification: "Capstone / Open Source" },
        { name: "SQL", evidenceLevel: 4, verification: "Production DB" },
        { name: "Data Analysis", evidenceLevel: 4, verification: "Published Research" },
        { name: "Tableau", evidenceLevel: 3, verification: "Certified Specialist" },
      ],
      applicationStatus: "INTERVIEW_SCHEDULED",
      notes: "Top-tier candidate. Completed high-scale ETL project. Excellent communication.",
    },
    {
      id: "std_001",
      name: "Aarav Sharma",
      institute: "IIITE Bengaluru",
      department: "Computer Science & Engineering",
      year: "4th Year",
      cgpa: 8.9,
      mandatoryMatch: 100,
      preferredMatch: 75,
      compositeScore: 92.5,
      gateStatus: "ELIGIBLE - HIGH GATE PASSED",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
      topSkills: [
        { name: "Python", evidenceLevel: 4, verification: "Project Verified" },
        { name: "Data Analysis", evidenceLevel: 4, verification: "Project Verified" },
        { name: "SQL", evidenceLevel: 3, verification: "Assessment Verified" },
        { name: "Power BI", evidenceLevel: 3, verification: "Assessment Verified" },
      ],
      applicationStatus: "SHORTLISTED",
      notes: "100% mandatory match on Data Analyst role. Clean code portfolio.",
    },
    {
      id: "std_007",
      name: "Kabir Reddy",
      institute: "IIITE Bengaluru",
      department: "Data Science & AI",
      year: "4th Year",
      cgpa: 9.1,
      mandatoryMatch: 100,
      preferredMatch: 80,
      compositeScore: 94.0,
      gateStatus: "ELIGIBLE - HIGH GATE PASSED",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
      topSkills: [
        { name: "Python", evidenceLevel: 4, verification: "Project Verified" },
        { name: "SQL", evidenceLevel: 3, verification: "Assessment Verified" },
        { name: "Data Analysis", evidenceLevel: 4, verification: "Project Verified" },
        { name: "Statistics", evidenceLevel: 3, verification: "Assessment Verified" },
      ],
      applicationStatus: "SHORTLISTED",
      notes: "Strong mathematical grounding. High problem-solving assessment score.",
    },
    {
      id: "std_005",
      name: "Vikram Gupta",
      institute: "IIITE Bengaluru",
      department: "Computer Science & Engineering",
      year: "4th Year",
      cgpa: 8.5,
      mandatoryMatch: 100,
      preferredMatch: 70,
      compositeScore: 91.0,
      gateStatus: "ELIGIBLE - HIGH GATE PASSED",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150",
      topSkills: [
        { name: "Python", evidenceLevel: 4, verification: "Project Verified" },
        { name: "SQL", evidenceLevel: 3, verification: "Assessment Verified" },
        { name: "React", evidenceLevel: 2, verification: "Course Certificate" },
        { name: "Docker", evidenceLevel: 2, verification: "Course Certificate" },
      ],
      applicationStatus: "APPLIED",
      notes: "Good dual skillset across data engineering and backend services.",
    },
  ],

  candidateComparison: {
    roleTitle: "Data Analyst Intern (opp_001)",
    candidates: [
      {
        id: "std_002",
        name: "Priya Patel",
        compositeScore: 100.0,
        mandatoryMatch: "100%",
        preferredMatch: "100%",
        cgpa: 9.4,
        assessmentScore: "96 / 100",
        evidenceLevelMax: 4,
        verifiedSkillsCount: 8,
        codingProficiency: "Expert (L4)",
        status: "Full Match — Ready to Hire",
      },
      {
        id: "std_001",
        name: "Aarav Sharma",
        compositeScore: 92.5,
        mandatoryMatch: "100%",
        preferredMatch: "75%",
        cgpa: 8.9,
        assessmentScore: "88 / 100",
        evidenceLevelMax: 4,
        verifiedSkillsCount: 7,
        codingProficiency: "Advanced (L3)",
        status: "Eligible — Shortlisted",
      },
      {
        id: "std_007",
        name: "Kabir Reddy",
        compositeScore: 94.0,
        mandatoryMatch: "100%",
        preferredMatch: "80%",
        cgpa: 9.1,
        assessmentScore: "91 / 100",
        evidenceLevelMax: 4,
        verifiedSkillsCount: 6,
        codingProficiency: "Advanced (L3)",
        status: "Eligible — Shortlisted",
      },
      {
        id: "std_003",
        name: "Rohan Verma",
        compositeScore: 0.0,
        mandatoryMatch: "75% (Missing SQL)",
        preferredMatch: "75%",
        cgpa: 7.8,
        assessmentScore: "72 / 100",
        evidenceLevelMax: 3,
        verifiedSkillsCount: 4,
        codingProficiency: "Intermediate (L2)",
        status: "Ineligible — Filtered Out by Gatekeeper",
      },
    ],
  },

  postInternshipEvaluations: [
    {
      id: "eval_001",
      studentId: "std_002",
      studentName: "Priya Patel",
      opportunityId: "opp_001",
      roleTitle: "Data Analyst Intern",
      period: "Feb 2026 – Aug 2026 (6 Months)",
      managerName: "Vikram Malhotra",
      skillsToElevate: [
        { skill: "Python", currentLevel: 4, proposedLevel: 5, status: "PENDING_SIGN_OFF" },
        { skill: "Data Analysis", currentLevel: 4, proposedLevel: 5, status: "PENDING_SIGN_OFF" },
        { skill: "SQL ETL", currentLevel: 4, proposedLevel: 5, status: "PENDING_SIGN_OFF" },
      ],
      performanceRating: 5.0,
      feedback: "Priya demonstrated senior-level ownership in refactoring our enterprise SQL warehouse pipelines and deploying automated KPI dashboards. Outstanding work.",
      status: "PENDING_SUBMISSION",
    },
    {
      id: "eval_002",
      studentId: "std_023",
      studentName: "Siddharth Rao",
      opportunityId: "opp_002",
      roleTitle: "Machine Learning Intern",
      period: "Mar 2026 – Aug 2026 (6 Months)",
      managerName: "Dr. Arvind Swaminathan",
      skillsToElevate: [
        { skill: "Machine Learning", currentLevel: 3, proposedLevel: 5, status: "PENDING_SIGN_OFF" },
        { skill: "PyTorch", currentLevel: 3, proposedLevel: 5, status: "PENDING_SIGN_OFF" },
      ],
      performanceRating: 4.8,
      feedback: "Developed lightweight transformer inference models with 35% latency reduction in production.",
      status: "PENDING_SUBMISSION",
    },
  ],
};

export const instituteData = {
  profile: {
    id: "inst_001",
    name: "Indian Institute of Information Technology & Engineering",
    shortName: "IIITE Bengaluru",
    code: "IIITE-BLR",
    nirfRank: 14,
    aisheCode: "U-0482",
    location: "Bengaluru, Karnataka",
    accreditation: "NAAC A++ | NBA Tier-1 Accredited",
    website: "https://iiite.ac.in",
    officialEmail: "placement@iiite.ac.in",
    contactPhone: "+91 80 2841 0001",
    totalStudents: 1840,
    facultyCount: 187,
    profileCompletion: 95,
    hodName: "Dr. Rajesh Kulkarni",
    hodRole: "Professor & Head of Placement and Industry Relations",
  },

  departmentReadiness: [
    {
      id: "dept_cse",
      name: "Computer Science & Engineering",
      code: "CSE",
      studentCount: 480,
      facultyCount: 42,
      readinessScore: 91,
      placementRate: "88.2%",
      averagePackage: "₹11.4 LPA",
      topStrength: "Full Stack Development & Cloud Architecture",
      primaryGapSkill: "Machine Learning & AI Modeling",
      activeWorkshops: 2,
    },
    {
      id: "dept_ds",
      name: "Data Science & Artificial Intelligence",
      code: "AI/DS",
      studentCount: 240,
      facultyCount: 24,
      readinessScore: 94,
      placementRate: "92.5%",
      averagePackage: "₹13.2 LPA",
      topStrength: "Data Analytics, Python & SQL Engineering",
      primaryGapSkill: "Distributed Spark & Cloud MLOps",
      activeWorkshops: 1,
    },
    {
      id: "dept_it",
      name: "Information Technology",
      code: "IT",
      studentCount: 320,
      facultyCount: 28,
      readinessScore: 87,
      placementRate: "84.0%",
      averagePackage: "₹9.8 LPA",
      topStrength: "Web Architecture, React & Database Systems",
      primaryGapSkill: "Docker & Containerization",
      activeWorkshops: 1,
    },
    {
      id: "dept_ece",
      name: "Electronics & Communication Engineering",
      code: "ECE",
      studentCount: 360,
      facultyCount: 35,
      readinessScore: 81,
      placementRate: "78.4%",
      averagePackage: "₹8.2 LPA",
      topStrength: "C++, Embedded Systems & IoT",
      primaryGapSkill: "PostgreSQL & Database Engineering",
      activeWorkshops: 1,
    },
    {
      id: "dept_mech",
      name: "Mechanical Engineering",
      code: "MECH",
      studentCount: 300,
      facultyCount: 30,
      readinessScore: 76,
      placementRate: "72.0%",
      averagePackage: "₹6.8 LPA",
      topStrength: "CAD Modeling & Industrial Robotics",
      primaryGapSkill: "Python for Engineering Analytics",
      activeWorkshops: 1,
    },
  ],

  skillGapAlerts: [
    {
      id: "alert_001",
      skillName: "Machine Learning",
      category: "Data Science & AI",
      affectedStudentCount: 91,
      department: "Computer Science & Engineering",
      priority: "HIGH",
      hasPII: false,
      kAnonymityScore: 91,
      suggestedAction: "1-Click Corporate Workshop Creator",
      message: "91 students in Computer Science are missing preferred skill 'Machine Learning' across 12 active enterprise internship postings.",
      industryDemandCount: 12,
      createdAt: "2026-08-20",
    },
    {
      id: "alert_002",
      skillName: "Docker & Containerization",
      category: "Cloud & DevOps",
      affectedStudentCount: 64,
      department: "Information Technology",
      priority: "MEDIUM",
      hasPII: false,
      kAnonymityScore: 64,
      suggestedAction: "Schedule Hands-on Cloud Bootcamp",
      message: "64 eligible students in IT are missing preferred skill 'Docker' across 8 backend and cloud opportunities.",
      industryDemandCount: 8,
      createdAt: "2026-08-21",
    },
    {
      id: "alert_003",
      skillName: "PostgreSQL Advanced Optimization",
      category: "Database & Querying",
      affectedStudentCount: 42,
      department: "Electronics & Communication",
      priority: "MEDIUM",
      hasPII: false,
      kAnonymityScore: 42,
      suggestedAction: "Add Elective Query Engineering Module",
      message: "42 students missing PostgreSQL in relational database applications.",
      industryDemandCount: 6,
      createdAt: "2026-08-22",
    },
    {
      id: "alert_004",
      skillName: "Power BI & Business Storytelling",
      category: "Data Science & AI",
      affectedStudentCount: 38,
      department: "Mechanical & Civil Engineering",
      priority: "LOW",
      hasPII: false,
      kAnonymityScore: 38,
      suggestedAction: "Host Micro-Certification Workshop",
      message: "38 students seeking data-driven operations roles lack Power BI visualization skills.",
      industryDemandCount: 5,
      createdAt: "2026-08-23",
    },
    {
      id: "alert_005",
      skillName: "Kubernetes & CI/CD Pipelines",
      category: "Cloud & DevOps",
      affectedStudentCount: 29,
      department: "Computer Science & Engineering",
      priority: "MEDIUM",
      hasPII: false,
      kAnonymityScore: 29,
      suggestedAction: "Corporate Partner Workshop Series",
      message: "29 high-GPA students lack cloud infrastructure deployment credentials.",
      industryDemandCount: 7,
      createdAt: "2026-08-24",
    },
  ],

  activeWorkshops: [
    {
      id: "tp_001",
      title: "Hands-on Applied Machine Learning with Scikit-Learn",
      targetSkill: "Machine Learning",
      targetDepartment: "Computer Science & Engineering",
      instructor: "Dr. Vikram Joshi & Apex Analytics Engineers",
      duration: "4 Weeks (32 Hours)",
      startDate: "2026-09-01",
      status: "SCHEDULED",
      enrolledCount: 78,
      maxCapacity: 100,
      sourceAlertId: "alert_001",
      completionCredential: "Level 3 Assessment Verified Badge",
    },
    {
      id: "tp_002",
      title: "Docker & Containerization Cloud Deployment Bootcamp",
      targetSkill: "Docker",
      targetDepartment: "Information Technology",
      instructor: "Prof. Shalini Rao",
      duration: "2 Weeks (16 Hours)",
      startDate: "2026-08-25",
      status: "IN_PROGRESS",
      enrolledCount: 52,
      maxCapacity: 60,
      sourceAlertId: "alert_002",
      completionCredential: "Level 3 Assessment Verified Badge",
    },
    {
      id: "tp_003",
      title: "PostgreSQL Query Tuning & Database Architecture",
      targetSkill: "PostgreSQL",
      targetDepartment: "Electronics & Communication",
      instructor: "Guest Expert - CloudPeak Systems",
      duration: "3 Weeks (20 Hours)",
      startDate: "2026-09-08",
      status: "SCHEDULED",
      enrolledCount: 40,
      maxCapacity: 50,
      sourceAlertId: "alert_003",
      completionCredential: "Level 3 Assessment Verified Badge",
    },
  ],

  placementStats: {
    overallPlacementRate: "88.4%",
    totalEligibleStudents: 1420,
    placedStudents: 1255,
    highestPackage: "₹24.5 LPA",
    averagePackage: "₹9.4 LPA",
    medianPackage: "₹8.5 LPA",
    activeRecruitingPartners: 48,
    internshipConversionRate: "76.2%",
  },

  employerFeedback: [
    {
      id: "fb_001",
      companyName: "Apex Analytics Corp",
      recruiterName: "Vikram Malhotra",
      rating: 5,
      comments: "IIITE students are outstanding. The 5-level skill verification system gave us 100% confidence in candidates' practical Python and SQL abilities.",
      endorsedSkills: ["Python", "Data Analysis", "SQL"],
      endorsementsIssued: 12,
      date: "2026-08-15",
    },
    {
      id: "fb_002",
      companyName: "FinTech Global Innovations",
      recruiterName: "Ananya Deshpande",
      rating: 5,
      comments: "Zero noise in candidate filtering. We interviewed 8 candidates and extended 6 offers within 48 hours.",
      endorsedSkills: ["SQL", "Excel Financial Modeling", "Power BI"],
      endorsementsIssued: 6,
      date: "2026-08-18",
    },
    {
      id: "fb_003",
      companyName: "CloudPeak Systems",
      recruiterName: "Ramesh Sen",
      rating: 4,
      comments: "Strong backend foundations. We recommend students participate more in Docker & Kubernetes containerization bootcamps.",
      endorsedSkills: ["Node.js", "PostgreSQL", "Linux"],
      endorsementsIssued: 8,
      date: "2026-08-20",
    },
  ],
};

export const adminData = {
  platformStats: {
    totalStudents: 4850,
    verifiedOrganizations: 128,
    accreditedInstitutes: 42,
    skillVerificationsIssued: 14620,
    activeOpportunities: 315,
    placementSuccessRate: "91.2%",
    zeroNoiseScreeningAccuracy: "99.8%",
    totalAssessmentsCompleted: 18450,
    systemUptime: "99.98%",
  },

  kycQueue: [
    {
      id: "kyc_001",
      entityName: "QuantumByte Solutions",
      entityType: "ORGANIZATION",
      sector: "DeepTech / Quantum Computing",
      taxIdGstin: "36AAACQ9876Q1ZB",
      registrationNumber: "U72900TG2022PTC160123",
      location: "Hyderabad, Telangana",
      submittedDate: "2026-08-23",
      status: "PENDING",
      riskScore: "LOW",
      documents: [
        { name: "Certificate of Incorporation (CIN).pdf", verified: true },
        { name: "GSTIN Registration Certificate.pdf", verified: true },
        { name: "Board Resolution for Recruitment.pdf", verified: false },
      ],
      actionsAvailable: ["APPROVE", "REJECT", "REQUEST_INFO"],
    },
    {
      id: "kyc_002",
      entityName: "AlphaMatrix AI Labs",
      entityType: "ORGANIZATION",
      sector: "Generative AI & LLM Systems",
      taxIdGstin: "07AABCA5432E1Z8",
      registrationNumber: "U74999DL2023PTC189012",
      location: "New Delhi, Delhi",
      submittedDate: "2026-08-22",
      status: "INFO_REQUESTED",
      riskScore: "MEDIUM",
      documents: [
        { name: "Certificate of Incorporation (CIN).pdf", verified: true },
        { name: "GSTIN Certificate (Needs Seal).pdf", verified: false },
      ],
      adminNote: "Please upload official GSTIN document with authorized signatory stamp.",
      actionsAvailable: ["APPROVE", "REJECT", "REQUEST_INFO"],
    },
    {
      id: "kyc_003",
      entityName: "St. Xavier Institute of Technical Studies",
      entityType: "INSTITUTE",
      sector: "Higher Technical Education",
      aisheCode: "C-12984",
      location: "Mumbai, Maharashtra",
      submittedDate: "2026-08-21",
      status: "APPROVED",
      riskScore: "LOW",
      documents: [
        { name: "AISHE Gazette Notification.pdf", verified: true },
        { name: "NAAC Accreditation Certificate (Grade A).pdf", verified: true },
      ],
      adminNote: "Verified against MHRD AISHE National Portal.",
      actionsAvailable: ["VIEW_AUDIT_TRAIL"],
    },
    {
      id: "kyc_004",
      entityName: "Apex Analytics Corp",
      entityType: "ORGANIZATION",
      sector: "Big Data & Enterprise Analytics",
      taxIdGstin: "29ABCDE1234F1Z5",
      registrationNumber: "U72200KA2021PTC145892",
      location: "Bengaluru, Karnataka",
      submittedDate: "2026-08-10",
      status: "APPROVED",
      riskScore: "LOW",
      documents: [
        { name: "COI.pdf", verified: true },
        { name: "GSTIN.pdf", verified: true },
      ],
      adminNote: "Verified enterprise employer partner.",
      actionsAvailable: ["VIEW_AUDIT_TRAIL"],
    },
    {
      id: "kyc_005",
      entityName: "CloudScale Systems",
      entityType: "ORGANIZATION",
      sector: "Cloud Infrastructure & DevOps",
      taxIdGstin: "27AABCC1122D1Z9",
      registrationNumber: "U72300MH2020PTC120456",
      location: "Pune, Maharashtra",
      submittedDate: "2026-08-12",
      status: "APPROVED",
      riskScore: "LOW",
      documents: [
        { name: "COI.pdf", verified: true },
        { name: "GSTIN.pdf", verified: true },
      ],
      adminNote: "Verified partner.",
      actionsAvailable: ["VIEW_AUDIT_TRAIL"],
    },
  ],

  auditLogs: [
    {
      id: "log_001",
      actor: "System Administrator (usr_adm_01)",
      role: "ADMIN",
      action: "KYC_APPROVE_ORGANIZATION",
      target: "comp_001 (Apex Analytics Corp)",
      ipAddress: "103.24.12.89",
      timestamp: "2026-08-24T18:30:00Z",
      severity: "LOW",
      status: "SUCCESS",
    },
    {
      id: "log_002",
      actor: "Security Engine (Automated Guard)",
      role: "SECURITY_DAEMON",
      action: "ATTEMPT_ADMIN_REGISTRATION_BLOCK",
      target: "usr_attacker_99 (POST /api/auth/signup-intent role=ADMIN)",
      ipAddress: "185.220.101.5",
      timestamp: "2026-08-24T17:15:22Z",
      severity: "HIGH",
      status: "BLOCKED_403",
    },
    {
      id: "log_003",
      actor: "Vikram Malhotra (usr_rec_01)",
      role: "INDUSTRY",
      action: "OPPORTUNITY_PUBLISHED",
      target: "opp_001 (Data Analyst Intern - 5 Openings)",
      ipAddress: "122.166.88.42",
      timestamp: "2026-08-24T15:10:00Z",
      severity: "INFO",
      status: "SUCCESS",
    },
    {
      id: "log_004",
      actor: "Dr. Rajesh Kulkarni (usr_fac_01)",
      role: "INSTITUTE",
      action: "TRAINING_PROGRAM_CREATED",
      target: "tp_001 (Applied ML Workshop - 100 seats)",
      ipAddress: "14.139.182.2",
      timestamp: "2026-08-24T12:00:00Z",
      severity: "INFO",
      status: "SUCCESS",
    },
    {
      id: "log_005",
      actor: "Aarav Sharma (usr_001)",
      role: "STUDENT",
      action: "APPLICATION_SUBMITTED",
      target: "opp_001 (Priority Gate Clearance: 100% Mandatory Match)",
      ipAddress: "106.51.240.11",
      timestamp: "2026-08-24T10:45:00Z",
      severity: "INFO",
      status: "SUCCESS",
    },
    {
      id: "log_006",
      actor: "Security Engine (Edge Middleware)",
      role: "SECURITY_DAEMON",
      action: "SUSPENDED_ACCOUNT_REDIRECT",
      target: "usr_susp_04 -> /account-suspended",
      ipAddress: "49.37.152.9",
      timestamp: "2026-08-24T09:20:14Z",
      severity: "MEDIUM",
      status: "ENFORCED",
    },
  ],

  systemHealth: {
    matchingEngine: { status: "OPERATIONAL", avgLatencyMs: 0.4, ruleGate: "100% High Priority Rule" },
    verificationEngine: { status: "OPERATIONAL", levelsActive: "1-5 Multi-Evidence Hierarchy" },
    edgeMiddleware: { status: "OPERATIONAL", partitionsGuarded: 4, tokenValidation: "Cryptographic HMAC" },
    databaseEngine: { status: "CONNECTED", dialect: "PostgreSQL / Neon Serverless (Drizzle ORM)" },
  },
};

export default {
  studentData,
  industryData,
  instituteData,
  adminData,
};
